name: tests

on: [pull_request, push]

env:
  FORCE_COLOR: 1

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['21']

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node }}
    - run: npm i
    - run: npm test --color=always

  automerge:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' && contains(github.head_ref, 'dependabot/github_actions') }}
        with:
          github-token: ${{secrets.github_token}}
